switch_idea/urls.py
from django.conf.urls import patterns, include, url
from pilot.models import JobPost


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'switch_idea.views.list_jobs', name='list_jobs'),  # HOMEPAGE, DUPLICATE OF VIEW ALL JOBS

    url(r'^job/(?P<id_job>[-\w]+)/$', 'switch_idea.views.job_detail'),  # VIEW SPECIFIC JOB
    url(r'^jobs', 'switch_idea.views.list_jobs', name='list_jobs'),  # VIEW ALL JOBS

    url(r'^login/$', 'switch_idea.views.user_login', name='user_login'),  # FILL OUT USER LOGIN FORM
    url(r'^auth/$', 'switch_idea.views.user_auth', name='user_auth'),  # AUTHORIZE USER AFTER LOGIN

    url(r'^logout/', 'switch_idea.views.user_logout', name='user_logout'),  # LOGOUT

    url(r'^registers/$', 'switch_idea.views.registerStudent', name='registerStudent'),  # REGISTER NEW STUDENT ACCOUNT
    url(r'^registere/$', 'switch_idea.views.registerEmployer', name='registerEmployer'),  # REGISTER NEW EMPLOYER ACCOUNT

    url(r'^create/$', 'switch_idea.views.create', name='create'),  # CREATE JOB POST FORM
    url(r'^createNewEmployer/$', 'switch_idea.views.create_no_auth', name='create_no_auth'),  # CREATE JOB POST FORM NOT LOGGED IN

    url(r'^apply/(?P<id_student>[-\w]+)/(?P<id_jobpost>[-\w]+)/$', 'switch_idea.views.apply', name='apply'),  # FILL IN JOB POST FORM
    url(r'^apply_request/(?P<id_jobpost>[-\w]+)/$', 'switch_idea.views.apply', name='apply'),  #  APPLY FOR JOB REQUEST

    url(r'^createstudent/$', 'switch_idea.views.create_student', name='create_student'),  # CREATE STUDENT ACCOUNT FORM
    url(r'^createemployer/$', 'switch_idea.views.create_employer', name='create_employer'),  # CREATE STUDENT ACCOUNT FORM

    url(r'^students/$', 'switch_idea.views.list_students', name='list_students'),  # LIST ALL STUDENTS
    url(r'^student/(?P<id_user>[-\w]+)/$', 'switch_idea.views.student_detail', name='student_detail'),  # STUDENT PROFILE

    url(r'^employers/$', 'switch_idea.views.list_employers', name='list_employers'),  # LIST ALL STUDENTS
    url(r'^employer/(?P<id_employer>[-\w]+)/$', 'switch_idea.views.employer_detail', name='student_detail'),  # EMPLOYER PROFILE
    url(r'^employeropenings/(?P<user_id>[-\w]+)/$', 'switch_idea.views.manage_openings', name='manage_openings'),  # EMPLOYER JOB OPENINGS

    url(r'^change_name/(?P<id_user>[-\w]+)/$', 'switch_idea.views.change_name', name='change_name'),  # EMPLOYER PROFILE
    url(r'^change_name_finished/$', 'switch_idea.views.change_name_finished', name='change_name_finished'),  # EMPLOYER PROFILE

    url(r'^change_cellphone/$', 'switch_idea.views.change_cellphone', name='change_cellphone'),  # EMPLOYER PROFILE
    url(r'^change_cellphone_finished/$', 'switch_idea.views.change_cellphone_finished', name='change_cellphone_finished'),  # EMPLOYER PROFILE

    url(r'^blog/$', 'switch_idea.views.list_blog', name='list_blog'),
    url(r'^blog/(?P<id_blog_post>[-\w]+)/$', 'switch_idea.views.blog_detail', name='list_blog'),

    url(r'^applicants/(?P<jobpost_id>[-\w]+)/$', 'switch_idea.views.list_applicants', name='list_applicants'),

    url(r'^admin/', include(admin.site.urls)),  # DJANGO ADMIN PANEL
)

pilot/models.py
from django.contrib.auth.models import User
from django.db import models
from time import time
import datetime


def get_upload_file_name(instance, filename):
    return "uploaded_files/%s_%s" % (str(time()).replace('.', '_'), filename)


class JobType(models.Model):
    title = models.CharField(max_length=250, help_text='Internship, Full-time, Part-time.')

    def __unicode__(self):
        return self.title


class Location(models.Model):
    title = models.CharField(max_length=250, help_text='Add items to the location drop down.')

    def __unicode__(self):
        return self.title


class Country(models.Model):
    title = models.CharField(max_length=250, help_text='Add items to the country list drop down.')

    def __unicode__(self):
        return self.title


class Student(models.Model):
    uid = models.ForeignKey(User)
    title = models.CharField(max_length=250, help_text='The student name.')
    resume = models.FileField(upload_to=get_upload_file_name)
    location = models.ForeignKey(Location)
    country = models.ForeignKey(Country)
    prim_interest = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    sec_interest = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    cellphone = models.IntegerField(default=0)
    email_verified = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title


class Employer(models.Model):
    uid = models.ForeignKey(User)
    company_name = models.CharField(max_length=250, help_text='(Apple, Microsoft, Sony, Nokia... etc)')
    thumbnail = models.FileField(upload_to=get_upload_file_name)
    e_description = models.TextField(max_length=250, help_text='The company description.')
    LinkedIn = models.CharField(max_length=250, help_text='The employers LinkedIn account.')
    website = models.CharField(max_length=250, help_text='The employers website.')
    Twitter = models.CharField(max_length=250, help_text='The employers Twitter.')
    Facebook = models.CharField(max_length=250, help_text='The employers Facebook.')
    email_verified = models.BooleanField(default=False)

    def __unicode__(self):
        return self.company_name

    def URL_to_view_openings(self):
        return '/employeropenings/' + str(self.uid.id)

    def phone_number(self):
        return self.uid.email


class Category(models.Model):
    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    description = models.TextField()

    def __unicode__(self):
        return self.title
        

class Skill(models.Model):
    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    description = models.TextField()

    def __unicode__(self):
        return self.title


class JobPost(models.Model):
    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    type = models.ForeignKey(JobType)
    is_premium = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    j_description = models.TextField()
    responsibilities = models.TextField()
    benefits_perks = models.TextField()
    location = models.ForeignKey(Location)
    skills = models.ManyToManyField(Skill)
    employer = models.ForeignKey(Employer, default=1)
    category = models.ForeignKey(Category, default=1)
    totalViews = models.IntegerField(default=0)
    applicants = models.IntegerField(default=0)
    compensation = models.IntegerField(default=0, help_text='Enter the amount in rupees here.')
    url = models.CharField(max_length=250, help_text='Redirect url.')
    deadline = models.DateTimeField(default=datetime.datetime.now() + datetime.timedelta(30))

    def company(self):
        return self.employer.company_name

    def URL_to_view_applicants(self):
        return '/employeropenings/' + str(self.employer.uid_id)

    def __unicode__(self):
        return self.title


class JobApplication(models.Model):
    student = models.ForeignKey(Student, default=1)
    jobpost = models.ForeignKey(JobPost, default=1)
    cover_letter = models.TextField()
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    def expiry_date(self):
        return self.jobpost.deadline

    def name(self):
        return self.student.title

    def job_post(self):
        return self.jobpost.title

    def total_applicants(self):
        return self.jobpost.applicants

    class Meta:
        get_latest_by = "pub_date"


class BlogPost(models.Model):
    title = models.CharField(max_length=250, help_text='The title of the blog post.')
    author = models.ForeignKey(User)
    body = models.TextField()
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    thumbnail = models.FileField(upload_to=get_upload_file_name)


class JobPostNewEmployer(models.Model):
    email = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    phone = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    first_name = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    last_name = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    password = models.CharField(max_length=250, help_text='Maximum 250 characters.')

    company_name = models.CharField(max_length=250, help_text='(Recruiter, Chief Executive Officer, etc...)')
    slug = models.SlugField(unique=True, help_text='url name for the employer.')
    thumbnail = models.FileField(upload_to=get_upload_file_name)
    e_description = models.TextField(max_length=250, help_text='The company description.')
    LinkedIn = models.CharField(max_length=250, help_text='The employers LinkedIn account.')
    website = models.CharField(max_length=250, help_text='The employers website.')
    Twitter = models.CharField(max_length=250, help_text='The employers Twitter.')
    Facebook = models.CharField(max_length=250, help_text='The employers Facebook.')

    title = models.CharField(max_length=250, help_text='Maximum 250 characters.')
    type = models.ForeignKey(JobType)
    is_premium = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    j_description = models.TextField()
    responsibilities = models.TextField()
    benefits_perks = models.TextField()
    location = models.ForeignKey(Location)
    skills = models.ManyToManyField(Skill)
    category = models.ForeignKey(Category, default=1)
    totalViews = models.IntegerField(default=0)
    applicants = models.IntegerField(default=0)
    compensation = models.IntegerField(default=0, help_text='Enter the amount in rupees here.')
    url = models.CharField(max_length=250, help_text='Redirect url.')
    deadline = models.DateTimeField(default=datetime.datetime.now)

    def __unicode__(self):
        return self.title

templates/apply.html
{% load staticfiles %}

<style>
body
{
	background-color:#d9edf7 !important;
}
</style>
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet" />

<form action="/apply/{{student_id}}/{{jobid}}" method="post" style="background-color:#d9edf7;" enctype="multipart/form-data">{% csrf_token %}
	<br>
	<table>
	{{form.as_table}}
	</table>
	<br>

	<button type="submit" class="btn btn-primary input-xlg">Apply</button>
	<br>
</form>

<script>
$( document ).ready(function() 
{
    $('#id_cover_letter').addClass('form-control input-lg');
    $('#id_cover_letter').css("height", "125px");
});	
</script>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Job Portal</title>

  <!-- styles -->
  <link href="{% static "css/bootstrap-tagsinput.css" %}" rel="stylesheet" />
  <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" />
  <link href="{% static "css/custom.css" %}" rel="stylesheet" />
  <link href="{% static "css/CSS3-Buttons.css" %}" rel="stylesheet" />
  <link href="{% static "css/jquery-ui-1.10.4.css" %}" rel="stylesheet" />
  <link href="{% static "css/social-buttons.css" %}" rel="stylesheet" />
  <link href="{% static "css/chosen.css" %}" rel="stylesheet" />
  <link href="{% static "css/font-awesome.css" %}" rel="stylesheet" />
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script type="text/javascript" src="js/html5shiv.js"></script>
  <![endif]-->

  <!-- fav and touch icons -->
  <link rel="shortcut icon" href="#" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="#" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="#" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="#" />
  <link rel="apple-touch-icon-precomposed" href="#" />
  <!-- Placed at the end of the document so the pages load faster -->
  <script type="text/javascript" src="{% static "js/jquery.1.10.2.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/html5shiv.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap-tagsinput.js" %}"></script>
  <script type="text/javascript" src="{% static "js/jquery-ui-1.10.4.js" %}"></script>
  
    <script type="text/javascript" src="{% static "js/chosen.jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "js/prism.js" %}"></script>

</head>

<body>



  <script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
  </script>



<div class="login-form">
<br><br><br>
				<div class="inner-login hidden-sm hidden-xs"
					   <br><br><br><br>
					   <form action="/auth/" method="get">
					    <input style="display:inline; width:38%;" name="username" type="text" class="form-control" id="exampleInputUsername1" placeholder="Email">
					   
					    <input style="display:inline; width:38%;" type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
					  	
					  	<button type="submit" class="btn btn-primary">Submit</button>
					   </form>
				</div>
				
				<div id="login-slide" class="inner-login hidden-md hidden-lg" style="width:90%;" >
					   <br><br><br><br>
					   <form action="/auth/" method="get">
					    <input style="display:inline; width:35%;" name="username" type="text" class="form-control" id="exampleInputUsername1" placeholder="Email">
					   
					    <input style="display:inline; width:35%;" type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
					  	
					  	<button type="submit" class="btn btn-primary">Submit</button>
					   </form>
				</div>
</div>

<div class="body-login">
	<!-- the top head -->
	<div class="navbar navbar-fixed-top" role="navigation">
		<div class="container">
	  		<div class="navbar-header">
		  		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			    </button>
		  		<!-- Be sure to leave the brand out there if you want it shown -->
	    		<a class="navbar-brand" href="/jobs/"
	    		style="background-repeat:no-repeat;background-image:url('/static/img/switchidea-logo.png'); background-size:contain; width:249px; height:54px; display:inline-block;"></a>
    		</div>

			  <!-- post or upload cv -->
			 <div class="collapse navbar-collapse navbar-ex1-collapse">
			 
			 

			  
			  
				<!-- the menu -->
		  		<div style="float:right;">
		  		{% if username %}
				  <button style="margin-top:10px; margin-right:70px;" type="button" class="btn btn-warning dropdown-toggle dropdown-menu-left hidden-lg" data-toggle="dropdown">
				     <b>{{ first_name }}</b> &nbsp;<span class="glyphicon glyphicon-user"> </span>
				  </button>
				  <button style="margin-top:10px;" type="button" class="btn btn-warning dropdown-toggle dropdown-menu-left visible-lg" data-toggle="dropdown">
				     <b>{{ first_name }}</b> &nbsp;<span class="glyphicon glyphicon-user"> </span>
				  </button>
				  <ul class="dropdown-menu" role="menu" style="float:right;">
				  {% if is_student == True %}
				  	<li><a href="/student/{{ uid }}"><b>Profile</b></a></li>
				  {% else %}
				    <li><a href="/employer/{{ uid }}"><b>Profile</b></a></li>
				  {% endif %}	    
				    <li class="divider"></li>
				    <li><a href="/logout/"><b>Sign out</b></a></li>
				  </ul>
		  		{% else %}
		        	<a href="/login/" id="btn-sign-in" class="btn btn-default navbar-btn"><b>Sign in</b> &nbsp;<span class="glyphicon glyphicon-log-in"> </span> </a>
		      		<a href="/registers/" class="btn btn-warning navbar-btn"><b>Sign up</b> &nbsp;<span class="glyphicon glyphicon-check"> </span> </a>
		      	{% endif %}
		      	</div>
		      	
			</div>
		</div><!-- /.container -->
	</div>
	<!-- /.navbar -->


								
						
								{% block content %}
								{% endblock %}

<script>
/*
$( document ).ready(function() 
{
	$("#btn-sign-in").click(function()
		{
		  $(".login-form").slideToggle();
		});
});
*/
</script>

	<!-- the footer -->
	<footer>
		<div class="container">
			<p class="pull-left">About | Terms | Privacy | FAQ | Support | Contact</p>
			<p class="pull-right">SwitchIdea &copy; 2014 All Rights Reserved</p>
		</div>
	</footer>

  <!-- Javascript
    ================================================== -->

</div>
</body>
</html>

templates/employer_list.html
{% extends "base.html" %}


{% block content %}
	<h2>Employers</h2>
		<p style="color:red;">
		{{error}}
		</p>

        Total Employers: {{ totalEmployers }} Total Employers Verified: {{ totalVerified }}  Total Employers Unverified: {{ totalUnverified }}


<table style="width:1200px">
    <tr>
        <td>Full Name</td>
        <td>Email Verified</td>
        <td>Company</td>
        <td>LinkedIn</td>
        <td>Website</td>
        <td>Twitter</td>
        <td>Facebook</td>
    </tr>
		{% for item in employers %}
			<tr>
				{% for info in user_employers %}
					{% if info.id == item.uid_id %}
						<td><a href="/employer/{{info.id}}">{{ info.first_name }} {{ info.last_name }}</a></td> <td>{{ item.email_verified }} </td>
					{% endif %}
				{% endfor %}
				<td>{{item.company_name}}</td>
                <td>{{item.LinkedIn}}</td>
				<td>{{item.website}}</td>
				<td>{{item.Twitter}}</td>
                <td>{{item.Facebook}}</td>
                <td>

                    {% for post in jobposts %}
                        {% if item.id == post.employer_id %}
                            {{ post.id }}
                        {% endif %}
                    {% endfor %}

                </td>
			</tr>
		{% endfor %}



</table>
{% endblock %}

templates/index.html
{{greet}}

templates/login_form.html
{% extends "base.html" %}


{% block content %}

	<!-- the middle contents -->
	<div class="contents">
		<section class="access">
		<br>
			<div class="container">
				<div class="content-inner-detail">
					<form role="form" action="/auth/" method="get">
						<legend>Sign in</legend>
						<div class="form-group">
					    <label for="exampleInputEmail1">Email</label>
					    <input type="text" class="form-control input-lg" id="username" placeholder="Email" name="username">
					  	</div>
					  	<div class="form-group">
					    <label for="exampleInputPassword1">Password</label>
					    <input type="password" class="form-control input-lg" id="exampleInputPassword1" placeholder="Password" id="password" name="password">
					  	</div>
					  	<button type="submit" class="btnblue btn-primary input-lg btn-block"><b>Submit</b> <span class="glyphicon glyphicon-chevron-right"></span></button>
					</form>
					
					{% if form.errors %}
						<p style="color:red;">Sorry, that's not a valid username or password</p>
					{% endif %}
	
				</div>
			</div>
		</section>
	</div><!-- /.contents -->
	
{% endblock %}

templates/newname_form.html
{% extends "base.html" %}


{% block content %}

<style>
label
{
float:left;
}

input.r
{
float:right;
}
</style>

	<br>
	<article style="height:380px;" class="coolshadow">
		<p style="color:red;">
		{{error}}
		</p>
		<br>
		<p style="color:#634271;">{{notice}}</p>
	<br>

		<div class="outer">
			<form style="float:left;" action="/change_name_finished/" method="get">
				<label for="first_name">First name:</label>
				<input class="r" type="text" name="first_name" value="" id="first_name">
				<br> <br>
				<label for="last_name">Last name:</label>
				<input class="r" type="last_name" name="last_name" value="" id="last_name">
				<br> <br>
				<input class="r" type="submit" value="submit" />
			</form>
		</div>

	</article>

{% endblock %}

templates/newphone_form.html
{% extends "base.html" %}


{% block content %}

<style>
label
{
float:left;
}

input.r
{
float:right;
}
</style>

	<br>
	<article style="height:380px;" class="coolshadow">
		<p style="color:red;">
		{{error}}
		</p>
		<br>
		<p style="color:#634271;">{{notice}}</p>
	<br>

		<div class="outer">
			<form style="float:left;" action="/change_cellphone_finished/" method="get">
				<label for="cellphone">Mobile Phone:</label>
				<input class="r" type="text" name="cellphone" value="" id="cellphone">
				<br> <br>
				<input class="r" type="submit" value="submit" />
			</form>
		</div>

	</article>

{% endblock %}

templates/newpost.html
{% extends "base.html" %}


{% block content %}	
<!-- the middle contents -->
	<div class="contents">
		<section id="post">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-md-3">
						<h3 class="sub-heading"><span class="yellowish">€99</span> for 30days</h3>
						<p><strong>How it works</strong></p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at augue metus, at aliquam leo. Nam ac justo nisl. Ut non orci odio. Praesent lobortis blandit lacus et consectetur. Etiam ac sagittis tortor. Vestibulum vestibulum sem nec purus congue cursus. Sed bibendum lectus id tellus egestas sit amet interdum leo fringilla. Fusce dictum neque ut massa facilisis nec mattis erat blandit. In vel vestibulum massa.</p>

						<p><strong>Benefits</strong></p>
						<ol>
							<li>Consectetur adipiscing elit.</li>
							<li>Consectetur elit.</li>
							<li>Consectetur adipiscing.</li>
							<li>Consectetur adipiscing elit.</li>
							<li>Adipiscing elit.</li>
							<li>Consectetur adipiscing elit.</li>
						</ol>
					</div>
					<div class="col-xs-12 col-md-9">
						<h3 class="sub-heading">Post a job</h3>
						<div class="content-inner-detail">
							<form action="/create/" method="post" enctype="multipart/form-data">{% csrf_token %}

							    <legend>Job description</legend>
								<div class="row">
						  			<div class="col-xs-12 col-md-6">
								    	<div class="form-group">
									    <label for="id_title">Job title</label>
									    {{form.title}} <!--<input type="text" class="form-control input-lg">-->
									    <small class="help-block">Example: "Front-End Developer".</small>
									  	</div>
							    	</div>
							    	
							    	<div class="col-xs-12 col-md-6">
							    		<div class="form-group">
							    		<label for="id_category">Category</label>
								    	{{form.category}}							    	
								    	</div>
							    	</div>
						    	</div>
						    	<div class="row">
						  			<div class="col-xs-12 col-md-6">
						  				<div class="form-group">
								    	{{form.type}}
								    	<small class="help-block">Hold "Shift" key for multi-select</small>
								    	</div>
							    	</div>
							    	<div class="col-xs-12 col-md-6">
							    		<div class="form-group">
								    	{{form.location}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>
						    	</div>
						    	<div class="row">
						  			<div class="col-xs-12 col-md-6">
						  				<div class="form-group">
								    	<label>Description</label>
								   		{{form.j_description}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>
							    	<div class="col-xs-12 col-md-6">
							    		<div class="form-group">
								    	<label>Responsibilities</label> <span><small>e.g. requirements</small></span>
								    	{{form.responsibilities}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>
						    	</div>
						    	
						    	<div class="row">
						  			<div class="col-xs-12 col-md-6">
						  				<div class="form-group">
								    	<label>Benefits &amp; Perks</label>
								   		{{form.benefits_perks}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>
							    	<div class="col-xs-12 col-md-6">
							    		<div class="form-group">
								    	<label>Redirect URL</label> <span><small>e.g. requirements</small></span>
								    	{{form.url}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>
						    	</div>
						    	
						    	<div class="row">
						  			<div class="col-xs-12 col-md-6">
						  				<div class="form-group">
								    	<label>Compensation</label>
								   		{{form.compensation}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>
						  			<div class="col-xs-12 col-md-6">
						  				<div class="form-group">
								    	<label>Compensation</label>
								   		{{form.skills}}
								    	<small class="help-block">Example block-level help text here.</small>
								    	</div>
							    	</div>

						    	</div>
						    	
						    	<br>
						    	</div>
						    	<br>
						    	<button type="submit" class="btn btn-primary input-lg">Submit post</button>
							</form>
							
				<ul class="errorlist">Errors:
				    {% for key, value in form.errors.items %}
				    <li>{% ifnotequal key '__all__' %}{{ key }}{% endifnotequal %} {{ value }}</ul>
				    {% endfor %}
				</ul>
							
				
				
				<script>
$( document ).ready(function() {
    $('#id_title').addClass('form-control input-lg');
    $('#id_category').addClass('form-control input-lg');
    $('#id_type').addClass('form-control input-lg');
    $('#id_location').addClass('form-control input-lg');
    $('#id_description').addClass('form-control input-lg');
    $('#id_responsibilities').addClass('form-control input-lg');
    
    $('#id_benefits_perks').addClass('form-control input-lg');
    $('#id_url').addClass('form-control input-lg');
    $('#id_compensation').addClass('form-control input-lg');
    $('#id_deadline').addClass('form-control input-lg');
});			
				</script>			
							

						</div>
					</div>
				</div>
			</div>
		</section>
	</div><!-- /.contents -->
	
{% endblock %}

templates/openings_list.html
{% extends "base.html" %}


{% block content %}
	<h2>Manage Openings</h2>	
		<ul>
            {{ employer.company_name }}'s total openings: {{ totalposts }} Total Active: {{ activeposts }} Total Expired: {{ expiredposts }} Total Premium: {{ totalpremium }}
			{% for post in jobposts %}
			<table style="width:1300px">
			
				<tr> 
				<td><b>Title</b></td> 
				<td><b>Applicants</b></td> 
				<td><b>Post Date</b></td> 
				<td><b>Expiry Date</b></td> 
				<td><b>Status</b></td> 
				<td><b>Actions</b></td> 
				</tr>
			
						<tr>
						<td>{{ post.title }}</td>  
						
						<td>{{ post.applicants }}</td>  
						
						<td>{{ post.pub_date }}</td>  
						
						<td>{{ post.deadline }}</td>  		
					
						<td>
						{% if post.is_approved == 0 %}
							Awaiting Approval,&nbsp;
						{% endif %}		
							
						{% if post.pub_date < post.deadline %}
							Active
						{% elif post.pub_date > post.deadline %}
							Expired
						{% endif %}
						</td>	
						
						<td><a href="/applicants/{{post.id}}">View</a></td>	
							
				</tr>
			</table>
			{% endfor %}
		</ul>
{% endblock %}